# Generated by Django 2.2.19 on 2022-12-28 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('posts', '0002_auto_20221228_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='group',
        ),
    ]
