# Generated by Django 4.1.6 on 2023-02-11 22:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0014_alter_comment_author_alter_comment_post_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(
                help_text="Введите текст", verbose_name="текст"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(
                help_text="Введите текст", verbose_name="текст"
            ),
        ),
    ]
